# Modify if you use a different port...
ports:
- port: 9081
tasks:
  - init: mvn install -DskipTests=false
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-maven